### ISSUE TITLE
Gorm 使用 carbon.ToDateTimeString 时报错， ToDateString 正常

### ISSUE THREAD

**Issue by zxdstyle** [golang-module/carbon#14]
模型定义：
```golang
type OperationLog struct {
	ID        int                     `json:"id" gorm:"primary_key;AUTO_INCREMENT"`
	UserId    int                     `json:"user_id" gorm:"-"`
	Path      string                  `json:"path" gorm:"-"`
	Method    string                  `json:"method" gorm:"-"`
	Ip        string                  `json:"ip" gorm:"-"`
	Input     JSON                    `json:"input" gorm:"-"`
	CreatedAt carbon.ToDateTimeString `json:"created_at"`
	UpdatedAt carbon.ToDateTimeString `json:"updated_at"`
}
```

错误内容：
```
2020/09/23 21:25:46 http: panic serving 127.0.0.1:62249: json: error calling MarshalJSON for type carbon.ToDateTimeString: invalid character '-' after top-level value
goroutine 91 [running]:
net/http.(*conn).serve.func1(0xc0000d0320)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x49e16c0, 0xc0028352c0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e9
go-admin/middleware.CustomError.func1(0xc000ace000)
	/Users/zxdstyle/go/go-admin/middleware/customerror.go:44 +0x5d3
panic(0x49e16c0, 0xc0028352c0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/gin-gonic/gin/render.JSON.Render(...)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/render/json.go:59
github.com/gin-gonic/gin.(*Context).Render(0xc000ace000, 0xc8, 0x4c34d80, 0xc0028191c0)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:841 +0x149
github.com/gin-gonic/gin.(*Context).JSON(...)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:884
go-admin/apis/user.Login(0xc000ace000)
	/Users/zxdstyle/go/go-admin/apis/user/login.go:21 +0x155
github.com/gin-gonic/gin.(*Context).Next(0xc000ace000)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
go-admin/middleware.RequestId.func1(0xc000ace000)
	/Users/zxdstyle/go/go-admin/middleware/requestid.go:24 +0x199
github.com/gin-gonic/gin.(*Context).Next(0xc000ace000)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
go-admin/middleware.Options(0xc000ace000)
	/Users/zxdstyle/go/go-admin/middleware/header.go:23 +0x3d
github.com/gin-gonic/gin.(*Context).Next(0xc000ace000)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
go-admin/middleware.NoCache(0xc000ace000)
	/Users/zxdstyle/go/go-admin/middleware/header.go:15 +0x16a
github.com/gin-gonic/gin.(*Context).Next(0xc000ace000)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
go-admin/middleware.CustomError(0xc000ace000)
	/Users/zxdstyle/go/go-admin/middleware/customerror.go:48 +0x4e
github.com/gin-gonic/gin.(*Context).Next(0xc000ace000)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
go-admin/middleware.LoggerToFile.func1(0xc000ace000)
	/Users/zxdstyle/go/go-admin/middleware/logger.go:22 +0x6b
github.com/gin-gonic/gin.(*Context).Next(0xc000ace000)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00043c3c0, 0xc000ace000)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x67a
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00043c3c0, 0x4c3b340, 0xc000aca000, 0xc0000d6100)
	/Users/zxdstyle/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0005660e0, 0x4c3b340, 0xc000aca000, 0xc0000d6100)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0000d0320, 0x4c3e600, 0xc000abc000)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
^C2020-09-23 21:26:00 Shutdown Server ...
^[[A2020-09-23 21:26:00.922 server.go:116: Server exiting
```

**Comment by leonsun88** [comment]
把database.go第62行改成 return []byte(fmt.Sprintf("\"%s\"", timeFormat)), nil， 就可以使用了

**Comment by zxdstyle** [comment]
![image](https://user-images.githubusercontent.com/38398954/94406685-f9ac1200-01a4-11eb-84ad-51409063382f.png)

看了下，现在好像就是这么写的，依然报错

**Comment by zxdstyle** [comment]
@gouguoyin 大佬有空看看呢

**Comment by gouguoyin** [comment]
> @gouguoyin 大佬有空看看呢

抽空我看下

**Comment by leonsun88** [comment]
`不好意思，把database.go第37行改成 return []byte(fmt.Sprintf("\"%s\"", timeFormat)), nil 就可以使用了`

**Comment by leonsun88** [comment]
> ![image](https://user-images.githubusercontent.com/38398954/94406685-f9ac1200-01a4-11eb-84ad-51409063382f.png)
> 
> 看了下，现在好像就是这么写的，依然报错

不好意思，之前写错了，把database.go第37行改成 return []byte(fmt.Sprintf("\"%s\"", timeFormat)), nil 就可以使用了

**Comment by zxdstyle** [comment]
@leonsun88 大佬会搞的话可以提个PR啊，我php转go的不太会，按理说我应该不能直接改这个包吧

**Comment by gouguoyin** [comment]
已修复
